// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Force synchronous load before any env() calls to avoid race conditions
config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations/db push (port 5432)
    // DATABASE_URL (pooler port 6543) cannot execute DDL statements
    url: env("DIRECT_URL"),
    // shadowDatabaseUrl: env(""),
  },
});
